### ISSUE TITLE
Check for previous position

### ISSUE THREAD

**Issue by DHoffm** [lorenzofox3/lrDragNDrop#14]
If an item is dragged at the same position it was before the item still switch places with the previous one. One solution on how to fix this?

**Comment by lorenzofox3** [comment]
I guess it depends on whether you insert it before or after the target item 
https://github.com/lorenzofox3/lrDragNDrop/blob/master/lrDragNDrop.js#L144

**Comment by DHoffm** [comment]
Thx. I solved it in a different way. I needed a class for the dragged item. I added:

element.addClass("dragged");

to the dragstart event.

On the drop event I checked if the item has this class and if so I skip the reordering.

I also added a dragend event to remove the class afterwards.
